name: Sync search - PR

# **What it does**: Tries running the sync-search when relevant files change.
# **Why we have it**: To test that the script works and the popular pages json is valid.
# **Who does it impact**: Docs engineering.

on:
  pull_request:
    paths:
      - script/search/parse-page-sections-into-records.js
      - script/search/popular-pages.js
      - lib/search/popular-pages.json
      # Ultimately, for debugging this workflow itself
      - .github/workflows/sync-search-pr.yml

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Setup node
        uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Cache nextjs build
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package*.json') }}

      - name: Build
        run: npm run build

      - name: Run sync-search
        env:
          # Set filtered to only these so it doesn't run for too long.
          LANGUAGE: en
          VERSION: free-pro-team@latest
        run: npm run sync-search
